version: '3'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa55w0rd123"
      MSSQL_PID: Express
    ports:
      - "1433:1433"

  identityserver:
    build: 
      context: .
      dockerfile: ./BackEnd/IdentityServer/Dockerfile
    ports:
      - "7000:80"
    depends_on:
      - ms-sql-server

  chat-api:
    build:
      context: .
      dockerfile: ./BackEnd/WebApi/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - identityserver

  ng-client:
    build:
      context: .
      dockerfile: ./FrontEnd/chat-app/Dockerfile
    ports:
      - "9000:80"
    depends_on:
      - chat-api
