// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Core.Entities.Chatroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Chatrooms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Name = "Rick and Morty group",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Braking Bad group",
                            Type = 1
                        });
                });

            modelBuilder.Entity("Core.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ChatroomId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeletedForEveryone")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeletedForSender")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit");

                    b.Property<int?>("RepliedMessageId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Text")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.HasKey("Id");

                    b.HasIndex("RepliedMessageId");

                    b.HasIndex("ChatroomId", "SenderId");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            PasswordHash = "AQAAAAEAACcQAAAAEEKgEY9POY3wYUKMQNkypFFtPuR7LePDw0PvLQMe2L3ZMEt4QaL6XPTuUsAOFtjlIQ==",
                            Username = "Rick Sanchez"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            PasswordHash = "AQAAAAEAACcQAAAAENl6gcU0usQADYG8wNtF/eaN+VWDQsHE0wjrxlsz0Dk4OTJq+z3MmAV8Neg4ENO8Ng==",
                            Username = "Morty Smith"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            PasswordHash = "AQAAAAEAACcQAAAAEDkUuZ+EL11qvW8yXp9Su78otx+XV5mQeiItxG/cmwM0j2Fjj2Q/cLV1FVrF1VF6Rw==",
                            Username = "Jerry Smith"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            PasswordHash = "AQAAAAEAACcQAAAAEPyqGa96o35hzkVZp695Tw7THbbHqXOb8O03CXy2VSVCIF9wlJvXC2Szq8I9Wa1qLg==",
                            Username = "Walter White"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            PasswordHash = "AQAAAAEAACcQAAAAEApHyhGY2e7DO6BulwKHw+9StQKfVMX3K2fVLxiTe/EtcJyLPsitjCpEEMkZv7xVCg==",
                            Username = "Jesse Pinkman"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            PasswordHash = "AQAAAAEAACcQAAAAEFmcSP4756peXtybrp0ob1IBxMeBnnZy/t2ZxIf+xHAmk7DpfohjkmlDkvRPd9yVzw==",
                            Username = "Saul Goodman"
                        });
                });

            modelBuilder.Entity("Core.Entities.UserChatroom", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ChatroomId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ChatroomId");

                    b.HasIndex("ChatroomId");

                    b.ToTable("UserChtatrooms", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            ChatroomId = 1
                        },
                        new
                        {
                            UserId = 2,
                            ChatroomId = 1
                        },
                        new
                        {
                            UserId = 2,
                            ChatroomId = 2
                        },
                        new
                        {
                            UserId = 3,
                            ChatroomId = 2
                        },
                        new
                        {
                            UserId = 4,
                            ChatroomId = 3
                        },
                        new
                        {
                            UserId = 5,
                            ChatroomId = 3
                        },
                        new
                        {
                            UserId = 4,
                            ChatroomId = 4
                        },
                        new
                        {
                            UserId = 6,
                            ChatroomId = 4
                        },
                        new
                        {
                            UserId = 5,
                            ChatroomId = 5
                        },
                        new
                        {
                            UserId = 6,
                            ChatroomId = 5
                        },
                        new
                        {
                            UserId = 1,
                            ChatroomId = 6
                        },
                        new
                        {
                            UserId = 2,
                            ChatroomId = 6
                        },
                        new
                        {
                            UserId = 3,
                            ChatroomId = 6
                        },
                        new
                        {
                            UserId = 4,
                            ChatroomId = 7
                        },
                        new
                        {
                            UserId = 5,
                            ChatroomId = 7
                        },
                        new
                        {
                            UserId = 6,
                            ChatroomId = 7
                        });
                });

            modelBuilder.Entity("Core.Entities.Message", b =>
                {
                    b.HasOne("Core.Entities.Message", "RepliedMessage")
                        .WithMany("Replies")
                        .HasForeignKey("RepliedMessageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Core.Entities.UserChatroom", "UserChatroom")
                        .WithMany("Messages")
                        .HasForeignKey("ChatroomId", "SenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("RepliedMessage");

                    b.Navigation("UserChatroom");
                });

            modelBuilder.Entity("Core.Entities.UserChatroom", b =>
                {
                    b.HasOne("Core.Entities.Chatroom", "Chatroom")
                        .WithMany("UserChatrooms")
                        .HasForeignKey("ChatroomId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Entities.User", "User")
                        .WithMany("UserChatrooms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Chatroom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.Chatroom", b =>
                {
                    b.Navigation("UserChatrooms");
                });

            modelBuilder.Entity("Core.Entities.Message", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.Navigation("UserChatrooms");
                });

            modelBuilder.Entity("Core.Entities.UserChatroom", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
